apimServiceName: apim-prod-demo
loggers:
    - name: apim-demo
      properties:
        loggerType: applicationInsights
        description: prod application insights
        resourceId: "/subscriptions/40f77b11-d38b-4231-aee3-7c4b23b76374/resourceGroups/apim-demo/providers/microsoft.insights/components/apim-demo"
        credentials:
          instrumentationKey: "{{Logger-Credentials--6442a40f217d20156c343078}}"
        isBuffered: true
    - name: event-hub-logger
      properties:
        loggerType: azureEventHub
        description: prod event hub
        credentials:
            connectionString: "{{Logger-Credentials--6655e6f6fb42681b6c022985}}"
            eventHubName: "apim-logs/apim-logs"   # The name of the event hub
            policyName: "send-apim-logs"  # The name of the shared access policy
        isBuffered: true
# namedValues:
#   - name: environment
#     properties:
#       displayName: environment
#       value: "https://www.search2.com"
#   - name: mysecretvalue
#     properties:
#       displayName: mysecretvalue
#       keyVault:
#         identityClientId: [identity client id goes here]
#         secretIdentifier: [your url here]
#   - name: testSecret
#     properties:
#       displayName: testSecret
#       value: "{#testSecretValue#}"
#   - name: helloworldfromfuncapp-key
#     properties:
#       displayName: helloworldfromfuncapp-key
#       value: "{#helloworldfromfuncappkey#}"
#   - name: 634e022983908257b35630b0
#     properties:
#       displayName: helloworldfromlogicapp_manual-invoke_634e022983908257b35630b0
#       value: "{#helloworldfromlogicapp#}"  
# diagnostics:
#    - name: applicationinsights
#      properties:
#        verbosity: Error
#        loggerId: "/subscriptions/[subscription Guid goes here]/resourceGroups/rg-apim-lab-prod/providers/Microsoft.ApiManagement/service/apim-prod-wk-05102022/loggers/apim-lab-prod-insights"
# backends:
#   - name: helloworldfromfuncapp
#     properties:
#       url: "https://helloworldfromprodfuncapp.azurewebsites.net/api"
#       resourceid: "https://management.azure.com/subscriptions/[subscription Guid goes here]/resourceGroups/rg-apim-lab-prod/providers/Microsoft.Web/sites/helloworldfromprodfuncapp"
#   - name: LogicApp_helloworldfromlogicapp_rg-apim-lab_77fadbdc74f14ce88962b34400a1f170
#     properties:
#       url: "https://prod-75.eastus.logic.azure.com/workflows/[guid goes here]/triggers"
#       resourceid: "https://management.azure.com/subscriptions/[subscription Guid goes here]/resourceGroups/rg-apim-lab-prod/providers/Microsoft.Logic/workflows/helloworldfromprodlogicapp"
# apis:
#   - name: demo-conference-api
#     diagnostics:
#       - name: applicationinsights
#         properties:
#           verbosity: Error
#           loggerId: "/subscriptions/[subscription Guid goes here]/resourceGroups/rg-apim-lab-prod/providers/Microsoft.ApiManagement/service/apim-prod-wk-05102022/loggers/apim-lab-prod-insights"
