openapi: 3.0.1
info:
  title: chatGPT
  description: ''
  version: '1.0'
paths:
  /*:
    post:
      summary: chatGPT
      description: chatGPT
      operationId: chatgpt
      parameters:
        - name: Content-Type
          in: header
          schema:
            enum:
              - ''
            type: ''
        - name: api-key
          in: header
          schema:
            enum:
              - ''
            type: ''
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]